### ISSUE TITLE
Error Installing VM with virtmanager (ChromeOS Flex)

### ISSUE THREAD

**Issue by gryffindro** [Fmstrat/winapps#355]
Currently I am running on ChromeOS Flex and have Crostini (aka Linux Subsystem) enabled. When attempting to install the VM through virtmanager I am met with an error mentioning something to do with security.
Here are the logs it provided in the dialogue:
```
Unable to complete install: 'Unable to set XATTR trusted.libvirt.security.dac on /var/lib/libvirt/qemu/domain-6-win10/master-key.aes: Operation not permitted'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2001, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 701, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 649, in _create_guest
    domain = self.conn.createXML(install_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4366, in createXML
    raise libvirtError('virDomainCreateXML() failed')
libvirt.libvirtError: Unable to set XATTR trusted.libvirt.security.dac on /var/lib/libvirt/qemu/domain-6-win10/master-key.aes: Operation not permitted
```
Not sure if this is where this needs to be posted but I thought I should try here first

**Comment by freechelmi** [comment]
Thanks all for your contributions

Winapps dev now takes place here https://github.com/winapps-org/winapps

So we can close this issue for good
